#!/usr/bin/env bash

help="
$(basename "$0") [-h] <file/path/of/dir> <command> -- run a command from some directory.
options:
    -h -- show help
"

while getopts ':h:' option; do 
    case "$option" in
    	h)
    		echo "$help"
		exit
    		;;
    	*)
    		echo "$help"
		exit
    		;;
    esac
done

if [ -z "$1" ] || [ -z "$2" ]; then
    echo "$help"
    exit 1
fi

destinacija="$1"
komanda="$2"

trenutniFP=$(pwd)

cd "$destinacija" || exit
$komanda
cd "$trenutniFP" || exit
